version: '3.8'

services:
  web:
    build: ./
    container_name: support_service_web
    command: bash entrypoint.sh
    volumes:
      - ./app/:/usr/src/app/
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: support_service_db
    volumes:
      - support_service_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: support_service_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
volumes:
  support_service_postgres_data: